import { Manrope } from "next/font/google";
import type { Metadata } from "next";
import "@/styles/globals.scss";
import AntdProvider from "@/providers/AntdRegistry";
import { NextAuthProvider } from "@/providers/NextAuthProvider";

const geistManrope = Manrope({
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistManrope.className}>
        <AntdProvider>
          <NextAuthProvider>
            {children}
          </NextAuthProvider>
        </AntdProvider>
      </body>
    </html>
  );
}